# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_remove_sales_sale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Stuff')),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.RemoveField(
            model_name='sales',
            name='market',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
