# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_auto_20170407_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Магазин', to='Store.Market'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='picture',
            field=models.ImageField(blank=True, upload_to='stuff_images', verbose_name='Каритнка'),
        ),
    ]
