# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20170407_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Мвгазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['created'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterModelOptions(
            name='stuff',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='market',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='created_date',
        ),
        migrations.AddField(
            model_name='market',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='market',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
