# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_auto_20170418_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
