# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_auto_20170418_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
