# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_auto_20170418_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена'),
        ),
    ]
