# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_auto_20170313_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(default='market', max_length=20),
        ),
    ]
