# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0005_remove_stuff_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
    ]
