# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0006_stuff_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='amount',
            field=models.PositiveIntegerField(default=0, max_length=4),
        ),
    ]
