# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0007_stuff_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
