# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0008_auto_20170316_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=200)),
                ('saled_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.Market')),
            ],
        ),
    ]
