# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0009_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='saled_date',
            new_name='sale_date',
        ),
    ]
