# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0010_auto_20170322_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sale_date',
        ),
    ]
