# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0014_auto_20170407_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.Market', verbose_name='Магазин'),
        ),
    ]
